export const ROUTE_HOME = '/'
export const ROUTE_CART = '/cart'
export const ROUTE_DEVELOPMENT = '/development'

export const ROUTE_CONTACT = '/contact'
export const APP_CONFIG_NAME = 'Shop Test'
export const API_URL = 'https://fakestoreapi.com'
export const API_CATEGORY = 'products/categories'
export const API_PRODUCT = 'products'
export const URL_DEFAULT_IMAGE = '/default_image.jpg'
